<script lang="ts" setup>
import type { ToonflowApi } from '#/api/toonflow';

import { onMounted, reactive, ref } from 'vue';

import { Page } from '@vben/common-ui';

import { Button, Empty, Form, Input, message, Modal, Popconfirm, Space, Tabs, Tag } from 'ant-design-vue';

import { deletePrompt, getPrompts, getSkillContent, getSkills, savePrompt, saveSkillContent } from '#/api/toonflow';

import '../shared/page-card.css';
import '../styles/toon-theme.css';
const loading=ref(false); const open=ref(false); const prompts=ref<ToonflowApi.Prompt[]>([]); const skills=ref<ToonflowApi.Skill[]>([]);
const form=reactive({id:undefined as number|undefined,name:'',type:'system',sourceKey:'',data:'',useData:''});
const skillOpen=ref(false); const skillSaving=ref(false); const skillPath=ref(''); const skillText=ref('');
const expandedPromptIds=ref(new Set<number>());
function togglePrompt(id:number){const next=new Set(expandedPromptIds.value);if(next.has(id))next.delete(id);else next.add(id);expandedPromptIds.value=next}
async function load(){loading.value=true;try{[prompts.value,skills.value]=await Promise.all([getPrompts(),getSkills()])}finally{loading.value=false}}
function edit(row?:Record<string, any>){Object.assign(form,row??{id:undefined,name:'',type:'system',sourceKey:'',data:'',useData:''});open.value=true}
async function save(){if(!form.name.trim())return message.warning('请输入提示词名称');await savePrompt(form);open.value=false;message.success('提示词已保存');await load()}
async function remove(id:number){await deletePrompt(id);message.success('提示词已删除');await load()}
async function editSkill(row:Record<string,any>){skillPath.value=row.path;skillText.value=await getSkillContent(row.path);skillOpen.value=true}
async function saveSkill(){skillSaving.value=true;try{await saveSkillContent(skillPath.value,skillText.value);skillOpen.value=false;message.success('Skill 已保存');await load()}finally{skillSaving.value=false}}
onMounted(load);
</script>
<template><Page auto-content-height class="toon-page"><div class="toonflow-page-shell"><div class="toon-header"><div><h1 class="toon-title">提示词与 Skill</h1><p class="toon-subtitle">管理 Agent 的固定提示词与可复用技能。</p></div><Space><Button @click="load">刷新</Button><Button class="toon-primary" type="primary" @click="edit()">＋ 新建提示词</Button></Space></div><Tabs><Tabs.TabPane key="prompts" tab="提示词"><Empty v-if="!loading&&prompts.length===0" description="暂无提示词"/><div v-else class="toon-grid"><article v-for="record in prompts" :key="record.id" class="prompt-card"><div class="prompt-card__head"><span>⌘</span><div><h3>{{record.name}}</h3><code>{{record.sourceKey||'未设置固定 Key'}}</code></div><Tag class="prompt-type"  :bordered="false">{{record.type}}</Tag></div><p class="prompt-preview" :class="{ expanded: expandedPromptIds.has(record.id) }">{{record.data||'暂无提示词内容'}}</p><div class="prompt-meta"><small>{{record.useData||'暂无使用说明'}}</small><Button size="small" type="link" @click="togglePrompt(record.id)">{{ expandedPromptIds.has(record.id) ? '收起' : '展开全文' }}</Button></div><Space><Button type="link" @click="edit(record)">编辑</Button><Popconfirm title="确认删除该提示词？" @confirm="remove(record.id)"><Button danger type="link">删除</Button></Popconfirm></Space></article></div></Tabs.TabPane><Tabs.TabPane key="skills" tab="Skill"><Empty v-if="!loading&&skills.length===0" description="暂无 Skill"/><div v-else class="toon-grid"><article v-for="record in skills" :key="record.id" class="prompt-card skill-card"><div class="prompt-card__head"><span>⚙</span><div><h3>{{record.name}}</h3><code>{{record.path}}</code></div><Tag class="skill-status" :class="{ enabled: record.state === 1 }" :bordered="false">{{record.state===1?'可用':'停用'}}</Tag></div><p>{{record.description||'暂无说明'}}</p><small>{{record.type}} · {{new Date(record.updateTime).toLocaleString()}}</small><Button type="link" @click="editSkill(record)">编辑内容</Button></article></div></Tabs.TabPane></Tabs></div><Modal v-model:open="open" :title="form.id?'编辑提示词':'新建提示词'" width="760px" @ok="save"><Form layout="vertical"><Form.Item label="名称" required><Input v-model:value="form.name"/></Form.Item><Form.Item label="固定 Key"><Input v-model:value="form.sourceKey" placeholder="后端读取使用，保存后请勿随意修改"/></Form.Item><Form.Item label="类型" required><Input v-model:value="form.type" placeholder="system / agent / production"/></Form.Item><Form.Item label="提示词内容"><Input.TextArea v-model:value="form.data" :rows="10"/></Form.Item><Form.Item label="使用说明"><Input.TextArea v-model:value="form.useData" :rows="3"/></Form.Item></Form></Modal><Modal v-model:open="skillOpen" :confirm-loading="skillSaving" :title="`编辑 Skill：${skillPath}`" width="900px" @ok="saveSkill"><Input.TextArea v-model:value="skillText" :rows="24" class="font-mono"/></Modal></Page></template>
<style scoped>.toonflow-page-shell{display:flex;flex-direction:column;min-height:100%;height:100%;min-width:0;padding:4px 2px 20px;overflow:auto}.prompt-card{display:flex;min-height:270px;flex-direction:column;padding:16px;border:1px solid var(--toon-line);border-radius:14px;background:var(--ant-color-bg-container);box-shadow:0 2px 8px rgb(15 23 42 / 4%);transition:border-color .2s,box-shadow .2s}.prompt-card:hover{border-color:var(--ant-color-primary-border);box-shadow:0 8px 20px rgb(15 23 42 / 8%)}.prompt-card__head{min-width:0;display:grid;align-items:center;gap:10px;grid-template-columns:38px minmax(0,1fr) auto}.skill-status{max-width:70px;overflow:hidden;margin:0;padding:1px 7px;border-radius:999px;color:var(--ant-color-text-tertiary);background:var(--ant-color-fill-secondary);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.skill-status.enabled{color:var(--ant-color-success);background:var(--ant-color-success-bg)}.prompt-type{margin:0;padding:1px 7px;border-radius:999px;color:var(--ant-color-primary);background:var(--ant-color-primary-bg);font-size:11px}.prompt-card__head>span:not(.prompt-type):not(.skill-status){display:grid;width:38px;height:38px;border:1px solid var(--ant-color-border-secondary);border-radius:10px;color:var(--ant-color-primary);background:var(--ant-color-primary-bg);font-size:17px;place-items:center}.prompt-card__head .prompt-type{max-width:88px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.prompt-card{overflow:hidden}.prompt-card h3{overflow:hidden;margin:0;font-size:14px;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.prompt-card code{display:block;overflow:hidden;margin-top:3px;color:var(--ant-color-text-tertiary);font-size:10px;text-overflow:ellipsis;white-space:nowrap}.prompt-card>p{overflow-wrap:anywhere;display:-webkit-box;height:84px;overflow:hidden;margin:14px 0 8px;padding:10px;border:1px solid var(--ant-color-border-secondary);border-radius:8px;color:var(--ant-color-text-secondary);background:var(--ant-color-fill-quaternary);font-size:12px;line-height:19px;-webkit-box-orient:vertical;-webkit-line-clamp:4}.prompt-card>.prompt-meta{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:18px}.prompt-card>.prompt-meta small{display:block;min-width:0;overflow:hidden;color:var(--ant-color-text-tertiary);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.prompt-card>.prompt-meta .ant-btn{flex:none;padding-inline:4px;font-size:11px}.prompt-card>small{display:block;min-height:18px;overflow:hidden;margin:0;color:var(--ant-color-text-tertiary);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.prompt-card>.prompt-preview.expanded{height:auto;max-height:360px;-webkit-line-clamp:unset;overflow:auto}.prompt-card>.ant-space{margin-top:auto;padding-top:10px;border-top:1px solid var(--ant-color-border-secondary)}.skill-card{min-height:220px}.skill-card>p{height:60px;-webkit-line-clamp:3}</style>
