<script lang="ts" setup>
import type { ToonflowApi } from '#/api/toonflow';

import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';

import { Page } from '@vben/common-ui';
import { AiModelTypeEnum } from '@vben/constants';

import { Alert, Button, Card, Empty, Input, InputNumber, List, message, Popconfirm, Select, Space, Switch, Table, Tabs, Tag } from 'ant-design-vue';

import { getModelSimpleList } from '#/api/ai/model/model';
import { clearAgentMemory, clearAllAgentMemory, getAgentDeployments, getAgentMemories, getAgentRuns, getAgentModelDetails, getAgentRunEvents, getPrompts, getSkills, retryAgent, updateAgentDeployment } from '#/api/toonflow';

import '../shared/page-card.css';
import '../styles/toon-theme.css';
import AgentRuntimeConfigPanel from './AgentRuntimeConfigPanel.vue';
import AgentRunEventDrawer from '../components/AgentRunEventDrawer.vue';

type ModelType=ToonflowApi.AgentDeployment['modelType'];
type ModelOption={label:string;value:number;capabilities?:string[]};
const loading=ref(false);const saving=ref(false);const agents=ref<ToonflowApi.AgentDeployment[]>([]);const baseline=ref<Record<number,string>>({});
const router=useRouter();
const memoryAgent=ref<'productionAgent'|'scriptAgent'>('scriptAgent');const isolationKey=ref('scriptAgent:1:project');const memories=ref<ToonflowApi.AgentMemory[]>([]);const memoryLoading=ref(false);
const runAgentType=ref<'productionAgent'|'scriptAgent'>('productionAgent');const runIsolationKey=ref('productionAgent:1:none');const runs=ref<ToonflowApi.AgentRun[]>([]);const runsLoading=ref(false);const agentDetails=ref<Record<string,any>>({});
const eventOpen=ref(false);const eventLoading=ref(false);const selectedRun=ref<ToonflowApi.AgentRun>();const runEvents=ref<ToonflowApi.AgentRunEvent[]>([]);
let eventTimer: number | undefined;
const models=ref<Record<ModelType,ModelOption[]>>({chat:[],image:[],speech:[],video:[]});
const prompts=ref<ToonflowApi.Prompt[]>([]);const skills=ref<ToonflowApi.Skill[]>([]);
const typeLabels:Record<ModelType,string>={chat:'文本',image:'图片',speech:'语音',video:'视频'};
const capabilityLabels:Record<string,string>={audio:'音频',image:'图像',video:'视频',text:'文本',streaming:'流式',vision:'视觉'};
const providerSummary=computed(()=>Object.entries(models.value).map(([type,items])=>({type:type as ModelType,label:typeLabels[type as ModelType],count:items.length,models:items.slice(0,4).map(item=>item.label),capabilities:[...new Set(items.flatMap(item=>item.capabilities??[]))]})));
const columns=[{title:'Agent',dataIndex:'name',width:190},{title:'层级',key:'role',width:100},{title:'类型',key:'type',width:90},{title:'用途',dataIndex:'description',width:280,ellipsis:true},{title:'统一模型',key:'model',width:240},{title:'温度',key:'temperature',width:110},{title:'最大 Token',key:'tokens',width:130},{title:'启用',key:'enabled',width:90}];
function options(agent:{modelType?:ModelType}){return models.value[agent.modelType??'chat']}
function deploymentRole(key:string){if(key.includes('supervisionAgent'))return '监督 Agent';if(key.includes('decisionAgent'))return '决策 Agent';if(key.includes(':'))return '子 Agent';return '主 Agent'}
function toOptions(items:Array<{id:number;name:string;platform:string;config?:{capabilities?:Record<string,boolean>}}>){return items.map(x=>({label:`${x.name} (${x.platform})`,value:x.id,capabilities:Object.entries(x.config?.capabilities??{}).filter(([,enabled])=>enabled).map(([key])=>key)}))}
function editable(row:ToonflowApi.AgentDeployment){return JSON.stringify([row.modelConfigId,row.temperature,row.maxOutputTokens,row.disabled,row.promptSourceKey,row.memoryScope,row.writePermissions])}
const changedRows=computed(()=>agents.value.filter(row=>baseline.value[row.id]!==editable(row)));
async function load(){loading.value=true;try{const[a,c,i,v,s,p,k]=await Promise.all([getAgentDeployments(),getModelSimpleList(AiModelTypeEnum.CHAT),getModelSimpleList(AiModelTypeEnum.IMAGE),getModelSimpleList(AiModelTypeEnum.VIDEO),getModelSimpleList(AiModelTypeEnum.VOICE),getPrompts(),getSkills()]);agents.value=a;prompts.value=p;skills.value=k;baseline.value=Object.fromEntries(a.map(row=>[row.id,editable(row)]));models.value={chat:toOptions(c),image:toOptions(i),video:toOptions(v),speech:toOptions(s)}}finally{loading.value=false}}
async function saveAll(){const rows=changedRows.value;if(!rows.length)return;if(rows.some(row=>!row.modelConfigId))return message.warning('变更项必须选择对应类型的模型');saving.value=true;try{await Promise.all(rows.map(row=>updateAgentDeployment({id:row.id,modelConfigId:row.modelConfigId,temperature:row.temperature,maxOutputTokens:row.maxOutputTokens,disabled:row.disabled,promptSourceKey:row.promptSourceKey,memoryScope:row.memoryScope,writePermissions:row.writePermissions})));message.success(`已保存 ${rows.length} 项模型配置`);await load()}finally{saving.value=false}}
async function loadMemories(){if(!isolationKey.value.trim())return message.warning('请输入隔离键');memoryLoading.value=true;try{memories.value=await getAgentMemories(memoryAgent.value,isolationKey.value.trim())}finally{memoryLoading.value=false}}
async function clearMemories(type:'all'|'message'|'summary'){await clearAgentMemory(memoryAgent.value,isolationKey.value.trim(),type);message.success('记忆已清除');await loadMemories()}
async function clearAllMemories(){const result=await clearAllAgentMemory(memoryAgent.value);message.success(`已清除 ${result.deleted} 条${memoryAgent.value==='scriptAgent'?'剧本':'生产'} Agent 记忆`);memories.value=[]}
async function loadRuns(){if(!runIsolationKey.value.trim())return message.warning('请输入运行隔离键');runsLoading.value=true;try{runs.value=await getAgentRuns(runAgentType.value,runIsolationKey.value.trim());agentDetails.value=await getAgentModelDetails(runAgentType.value)}finally{runsLoading.value=false}}
async function retryRun(id:number){await retryAgent(id);message.success('已创建重试任务');await loadRuns()}
async function refreshRunEvents(){if(!selectedRun.value)return;const afterId=runEvents.value.at(-1)?.id??0;const events=await getAgentRunEvents(selectedRun.value.id,afterId);if(events.length)runEvents.value=[...runEvents.value,...events]}
async function showRun(run:ToonflowApi.AgentRun){selectedRun.value=run;eventOpen.value=true;eventLoading.value=true;window.clearInterval(eventTimer);try{runEvents.value=await getAgentRunEvents(run.id)}finally{eventLoading.value=false}if(['running','pending'].includes(run.state))eventTimer=window.setInterval(()=>void refreshRunEvents(),3000)}
onMounted(load);
onBeforeUnmount(()=>window.clearInterval(eventTimer));
</script>
<template><Page auto-content-height class="toon-page"><div class="toonflow-page-shell"><div class="toon-header"><div><h1 class="toon-title">Toonflow 设置</h1><p class="toon-subtitle">统一管理模型能力、Agent 运行时、提示词、技能和记忆。</p></div><Button @click="load" :loading="loading">刷新配置</Button></div><div class="settings-overview"><Card size="small"><b>{{ agents.length }}</b><span>Agent 配置</span></Card><Card size="small"><b>{{ prompts.length }}</b><span>可用 Prompt</span></Card><Card size="small"><b>{{ skills.length }}</b><span>可用 Skill</span></Card><Card size="small" :class="{ 'has-changes': changedRows.length }"><b>{{ changedRows.length }}</b><span>待保存修改</span></Card></div><Tabs>
<Tabs.TabPane key="models" tab="模型配置"><div class="section-heading"><div><h3>Agent 模型</h3><p>只配置 Agent 使用的模型、生成参数和启用状态；Prompt、Skill、记忆与权限请在 Agent 编排中设置。</p></div><Button class="toon-primary" type="primary" :disabled="changedRows.length === 0" :loading="saving" @click="saveAll">保存 {{ changedRows.length || '' }}</Button></div><Table :scroll="{ x: 1100, y: 460 }" sticky :columns="columns" :data-source="agents" :loading="loading" :pagination="false" row-key="id"><template #bodyCell="{column,record}"><Tag v-if="column.key === 'role'" :color="record.key.includes('supervisionAgent')?'orange':record.key.includes(':')?'blue':'green'">{{ deploymentRole(record.key) }}</Tag><Tag v-else-if="column.key === 'type'">{{ typeLabels[record.modelType as ModelType] }}</Tag><Select v-else-if="column.key === 'model'" v-model:value="record.modelConfigId" class="w-full" :options="options(record)" :placeholder="`选择${typeLabels[record.modelType as ModelType]}模型`" /><InputNumber v-else-if="column.key === 'temperature' && record.modelType === 'chat'" v-model:value="record.temperature" :min="0" :max="2" /><InputNumber v-else-if="column.key === 'tokens' && record.modelType === 'chat'" v-model:value="record.maxOutputTokens" :min="1" /><span v-else-if="column.key === 'temperature' || column.key === 'tokens'">—</span><Switch v-else-if="column.key === 'enabled'" :checked="!record.disabled" @update:checked="record.disabled = !$event" /></template></Table></Tabs.TabPane>
<Tabs.TabPane key="agents" tab="Agent 编排"><Alert message="主 Agent → 子 Agent → 监督 Agent" description="这里展示指定隔离键下的运行链路。具体子 Agent 工具由后端工作流运行时安全调度，运行结果会写回项目工作区。" show-icon /><AgentRuntimeConfigPanel class="mt-4" :agents="agents" :prompts="prompts" :skills="skills" /><div class="memory-toolbar mt-4"><Select v-model:value="runAgentType" :options="[{label:'剧本 Agent',value:'scriptAgent'},{label:'生产 Agent',value:'productionAgent'}]" style="width:160px" /><Input v-model:value="runIsolationKey" placeholder="例如 productionAgent:1:1" style="max-width:360px" /><Button :loading="runsLoading" @click="loadRuns">查看运行记录</Button></div><Card v-if="agentDetails.name || agentDetails.description" size="small" class="mb-3"><b>{{ agentDetails.name || runAgentType }}</b><p class="detail-muted">{{ agentDetails.description || '使用当前 Agent 的系统配置' }}</p></Card><Empty v-if="!runsLoading && runs.length===0" description="暂无 Agent 运行记录" /><List v-else :data-source="runs" :loading="runsLoading"><template #renderItem="{item}"><List.Item><List.Item.Meta :title="item.retryOfId ? `${item.agentType} · #${item.id} · 重试自 #${item.retryOfId}` : `${item.agentType} · #${item.id}`" :description="item.input"><template #avatar><Tag :color="item.state==='completed'?'green':item.state==='failed'?'red':item.state==='running'?'blue':'default'">{{ item.state }}</Tag></template></List.Item.Meta><template #actions><Button type="link" @click="showRun(item)">事件</Button><Button v-if="['failed','cancelled'].includes(item.state)" type="link" @click="retryRun(item.id)">重试</Button></template></List.Item></template></List></Tabs.TabPane>
<Tabs.TabPane key="memory" tab="Agent 记忆"><div class="memory-toolbar"><Select v-model:value="memoryAgent" :options="[{label:'剧本 Agent',value:'scriptAgent'},{label:'生产 Agent',value:'productionAgent'}]" style="width:160px" /><Input v-model:value="isolationKey" placeholder="隔离键，例如 scriptAgent:1:project" style="max-width:360px" /><Button :loading="memoryLoading" @click="loadMemories">查看记忆</Button><Popconfirm title="确认清除当前隔离键的全部记忆？" @confirm="clearMemories('all')"><Button danger>清空全部</Button></Popconfirm><Popconfirm :title="`确认清除当前${memoryAgent==='scriptAgent'?'剧本':'生产'} Agent 的全部记忆？此操作不可恢复。`" @confirm="clearAllMemories"><Button danger type="dashed">清空当前 Agent 全部记忆</Button></Popconfirm></div><Empty v-if="!memoryLoading && memories.length===0" description="暂无记忆，输入隔离键后查询" /><List v-else :data-source="memories" :loading="memoryLoading"><template #renderItem="{item}"><List.Item><template #actions><Popconfirm title="清除此类型的记忆？" @confirm="clearMemories(item.memoryType)"><Button danger type="link">清除此类</Button></Popconfirm></template><List.Item.Meta :description="new Date(item.createTime).toLocaleString()"><template #title><Tag>{{ item.memoryType==='summary'?'摘要':'消息' }}</Tag> {{ item.role }}</template></List.Item.Meta><pre class="memory-content">{{ item.content }}</pre></List.Item></template></List></Tabs.TabPane>
<Tabs.TabPane key="providers" tab="供应商"><Alert message="供应商由系统 AI 模块统一管理" description="Toonflow 只读使用已配置的厂商和模型，不在业务页面在线编写供应商代码。模型密钥、接口地址和启停状态请在 AI 模型中心维护。" show-icon /><div class="provider-grid"><Card v-for="item in providerSummary" :key="item.type" size="small" :title="item.label + '模型'"><template #extra><Tag color="blue">{{ item.count }} 个</Tag></template><div v-if="item.models.length" class="provider-models"><Tag v-for="name in item.models" :key="name">{{ name }}</Tag></div><div v-if="item.capabilities.length" class="provider-models provider-capabilities"><Tag v-for="capability in item.capabilities" :key="capability" color="green">{{ capabilityLabels[capability] || capability }}</Tag></div><Empty v-else :image="Empty.PRESENTED_IMAGE_SIMPLE" description="未配置" /></Card></div><Space class="mt-4"><Button type="primary" @click="router.push('/ai/console/model')">前往 AI 模型配置</Button><Button @click="load">重新读取模型</Button></Space></Tabs.TabPane>
</Tabs></div><AgentRunEventDrawer :open="eventOpen" :run-id="selectedRun?.id" :state="selectedRun?.state" :events="runEvents" :loading="eventLoading" @close="eventOpen = false" @refresh="refreshRunEvents" /></Page></template>
<style scoped>.toonflow-page-shell{display:flex;flex-direction:column;min-width:0;min-height:100%;height:100%;overflow:auto;padding:4px 2px 20px}.toonflow-page-shell :deep(.ant-table-wrapper){max-width:100%;overflow-x:auto}.toonflow-page-shell :deep(.ant-table-wrapper){max-width:100%;overflow-x:auto}.toonflow-page-shell :deep(.ant-table-content){overflow-x:auto!important}.toonflow-page-shell :deep(.ant-table-content::-webkit-scrollbar){height:8px}.toonflow-page-shell :deep(.ant-table-content::-webkit-scrollbar-thumb){border-radius:4px;background:#cbd5e1}.toon-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:16px}.settings-overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.settings-overview b{display:block;color:var(--ant-color-primary);font-size:22px}.settings-overview span{color:var(--ant-color-text-secondary);font-size:12px}.section-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:16px}.section-heading h3{margin:0}.section-heading p{margin:4px 0 0;color:var(--ant-color-text-secondary);font-size:12px}.memory-toolbar{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.memory-content{max-width:100%;margin:0;padding:10px;white-space:pre-wrap;background:var(--ant-color-fill-quaternary)}.provider-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin-top:16px}.provider-models{display:flex;flex-wrap:wrap;gap:6px}.detail-muted{margin:4px 0;color:var(--ant-color-text-secondary)}.run-output,.event-text{max-height:240px;overflow:auto;padding:10px;white-space:pre-wrap;background:var(--ant-color-fill-quaternary);font:12px/1.6 monospace}@media (max-width:800px){.settings-overview{grid-template-columns:repeat(2,minmax(0,1fr))}.toon-header,.section-heading{flex-direction:column}}</style>
