<script lang="ts" setup>
import type { ToonflowApi } from '#/api/toonflow';
import { computed, onMounted, reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { Button, Card, Form, Input, Modal, Popconfirm, Space, Table, Tabs, Tag, message } from 'ant-design-vue';
import { deleteCreativeManual, getCreativeManuals, saveCreativeManual } from '#/api/toonflow';

const loading=ref(false),open=ref(false),activeKind=ref<'director'|'visual'>('visual'),manuals=ref<ToonflowApi.CreativeManual[]>([]);
const form=reactive({id:undefined as number|undefined,kind:'visual' as 'director'|'visual',name:'',path:'',imagesText:'',data:[] as Array<{label:string;value:string;data:string}>});
const visualFields=[['README','README'],['前缀','prefix'],['角色','art_character'],['角色衍生','art_character_derivative'],['道具','art_prop'],['道具衍生','art_prop_derivative'],['场景','art_scene'],['场景衍生','art_scene_derivative'],['分镜','director_storyboard'],['分镜视频','art_storyboard_video'],['技法-导演规划','director_planning_style'],['技法-分镜表设计','director_storyboard_table_style']];
const directorFields=[['README','README'],['导演规划','director_planning_narrative'],['分镜表','director_storyboard_table_narrative']];
const filtered=computed(()=>manuals.value.filter(item=>item.kind===activeKind.value));
const columns=[{title:'名称',dataIndex:'name',width:220},{title:'标识',dataIndex:'path',width:230},{title:'内容项',key:'items',width:100},{title:'参考图',key:'images',width:100},{title:'更新时间',key:'updateTime',width:180},{title:'操作',key:'action',width:150}];
async function load(){loading.value=true;try{manuals.value=await getCreativeManuals()}finally{loading.value=false}}
function defaults(kind:'director'|'visual'){return (kind==='visual'?visualFields:directorFields).map(([label,value])=>({label:label!,value:value!,data:''}))}
function edit(row?:Record<string,any>){const kind=(row?.kind??activeKind.value) as 'director'|'visual';Object.assign(form,{id:row?.id,kind,name:row?.name??'',path:row?.path??'',imagesText:(row?.images??[]).join('\n'),data:row?.data?.length?JSON.parse(JSON.stringify(row.data)):defaults(kind)});open.value=true}
async function save(){if(!form.name.trim()||!form.path.trim())return message.warning('请输入名称和标识');await saveCreativeManual({id:form.id,kind:form.kind,name:form.name,path:form.path,images:form.imagesText.split('\n').map(v=>v.trim()).filter(Boolean),data:form.data});open.value=false;message.success('创作手册已保存');await load()}
async function remove(row:Record<string,any>){await deleteCreativeManual(row.kind as 'director'|'visual',row.path);message.success('创作手册已删除');await load()}
onMounted(load);
</script>
<template><Page auto-content-height><Card :bordered="false"><template #title>创作手册</template><template #extra><Space><Button @click="load">刷新</Button><Button type="primary" @click="edit()">新建{{activeKind==='visual'?'视觉':'导演'}}手册</Button></Space></template><Tabs v-model:active-key="activeKind"><Tabs.TabPane key="visual" tab="视觉手册"/><Tabs.TabPane key="director" tab="导演手册"/></Tabs><Table :columns="columns" :data-source="filtered" :loading="loading" row-key="id"><template #bodyCell="{column,record}"><template v-if="column.key==='items'"><Tag>{{record.data?.length??0}}</Tag></template><template v-if="column.key==='images'">{{record.images?.length??0}} 张</template><template v-if="column.key==='updateTime'">{{new Date(record.updateTime).toLocaleString()}}</template><template v-if="column.key==='action'"><Button type="link" @click="edit(record)">编辑</Button><Popconfirm title="确认删除该创作手册？" @confirm="remove(record)"><Button danger type="link">删除</Button></Popconfirm></template></template></Table></Card><Modal v-model:open="open" :title="`${form.id?'编辑':'新建'}${form.kind==='visual'?'视觉':'导演'}手册`" width="900px" @ok="save"><Form layout="vertical"><div class="grid grid-cols-2 gap-4"><Form.Item label="显示名称" required><Input v-model:value="form.name"/></Form.Item><Form.Item label="唯一标识" required><Input v-model:value="form.path" :disabled="!!form.id" placeholder="英文或拼音，不能包含路径符号"/></Form.Item></div><Form.Item label="参考图 URL（每行一个）"><Input.TextArea v-model:value="form.imagesText" :rows="3"/></Form.Item><Tabs><Tabs.TabPane v-for="item in form.data" :key="item.value" :tab="item.label"><Input.TextArea v-model:value="item.data" :rows="12" :placeholder="`${item.label} Markdown 内容`"/></Tabs.TabPane></Tabs></Form></Modal></Page></template>
