-- Durable, versioned episode-level video exports.
--
-- The composite script index allows the foreign key below to guarantee that a
-- render can never point at a script from a different project.
CREATE UNIQUE INDEX IF NOT EXISTS uq_toonflow_scripts_id_project_id
    ON toonflow.scripts(id, project_id);

-- Export result metadata can contain a complete source-video list and a long
-- object URL, so the former 255-character task field is not sufficient.
ALTER TABLE toonflow.tasks
    ALTER COLUMN related_objects TYPE text;

CREATE TABLE IF NOT EXISTS toonflow.episode_renders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL,
    script_id bigint NOT NULL,
    version integer NOT NULL,
    object_path text NOT NULL,
    file_path text NOT NULL,
    cover_path text,
    status text NOT NULL DEFAULT 'ready',
    source_video_ids bigint[] NOT NULL DEFAULT '{}'::bigint[],
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_current boolean NOT NULL DEFAULT false,
    created_by uuid NOT NULL,
    export_task_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT episode_renders_project_fk
        FOREIGN KEY (project_id)
        REFERENCES toonflow.projects(id)
        ON DELETE CASCADE,
    CONSTRAINT episode_renders_script_project_fk
        FOREIGN KEY (script_id, project_id)
        REFERENCES toonflow.scripts(id, project_id)
        ON DELETE CASCADE,
    CONSTRAINT episode_renders_export_task_fk
        FOREIGN KEY (export_task_id)
        REFERENCES toonflow.tasks(id)
        ON DELETE SET NULL,
    CONSTRAINT episode_renders_version_positive CHECK (version > 0),
    CONSTRAINT episode_renders_object_path_not_blank CHECK (btrim(object_path) <> ''),
    CONSTRAINT episode_renders_file_path_not_blank CHECK (btrim(file_path) <> ''),
    CONSTRAINT episode_renders_status_valid
        CHECK (status IN ('processing', 'ready', 'failed', 'archived')),
    CONSTRAINT episode_renders_current_is_ready
        CHECK (NOT is_current OR status = 'ready'),
    CONSTRAINT episode_renders_metadata_is_object
        CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT episode_renders_project_script_version_unique
        UNIQUE (project_id, script_id, version),
    CONSTRAINT episode_renders_export_task_unique UNIQUE (export_task_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_toonflow_episode_renders_current
    ON toonflow.episode_renders(project_id, script_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_toonflow_episode_renders_project_created
    ON toonflow.episode_renders(project_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_toonflow_episode_renders_script_version
    ON toonflow.episode_renders(project_id, script_id, version DESC);

CREATE INDEX IF NOT EXISTS idx_toonflow_episode_renders_created_by
    ON toonflow.episode_renders(created_by, created_at DESC);
