-- Repair OAuth2 token sequences omitted from the consolidated baseline.
CREATE SEQUENCE IF NOT EXISTS public.system_oauth2_access_token_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_oauth2_refresh_token_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_dict_data_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_login_log_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_mail_log_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_notify_message_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_operate_log_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_sms_log_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_tenant_package_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_tenant_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_user_post_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_user_role_seq;
CREATE SEQUENCE IF NOT EXISTS public.system_users_seq;

SELECT setval(
    'public.system_oauth2_access_token_seq',
    GREATEST(COALESCE((SELECT MAX(id) FROM public.system_oauth2_access_token), 0), 1),
    EXISTS (SELECT 1 FROM public.system_oauth2_access_token)
);

DO $$
DECLARE
    sequence_table text[];
    maximum_id bigint;
    has_rows boolean;
BEGIN
    FOREACH sequence_table SLICE 1 IN ARRAY ARRAY[
        ['system_dict_data_seq', 'system_dict_data'],
        ['system_login_log_seq', 'system_login_log'],
        ['system_mail_log_seq', 'system_mail_log'],
        ['system_notify_message_seq', 'system_notify_message'],
        ['system_operate_log_seq', 'system_operate_log'],
        ['system_sms_log_seq', 'system_sms_log'],
        ['system_tenant_package_seq', 'system_tenant_package'],
        ['system_tenant_seq', 'system_tenant'],
        ['system_user_post_seq', 'system_user_post'],
        ['system_user_role_seq', 'system_user_role'],
        ['system_users_seq', 'system_users']
    ]
    LOOP
        EXECUTE format(
            'SELECT COALESCE(MAX(id), 0), EXISTS (SELECT 1 FROM public.%I) FROM public.%I',
            sequence_table[2],
            sequence_table[2]
        ) INTO maximum_id, has_rows;
        PERFORM setval(
            format('public.%I', sequence_table[1])::regclass,
            GREATEST(maximum_id, 1),
            has_rows
        );
    END LOOP;
END $$;
SELECT setval(
    'public.system_oauth2_refresh_token_seq',
    GREATEST(COALESCE((SELECT MAX(id) FROM public.system_oauth2_refresh_token), 0), 1),
    EXISTS (SELECT 1 FROM public.system_oauth2_refresh_token)
);

CREATE TABLE IF NOT EXISTS toonflow.workflow_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES toonflow.projects(id) ON DELETE CASCADE,
    script_id bigint NOT NULL REFERENCES toonflow.scripts(id) ON DELETE CASCADE,
    version integer NOT NULL CHECK (version > 0),
    schema_version integer NOT NULL DEFAULT 1 CHECK (schema_version > 0),
    definition jsonb NOT NULL DEFAULT '{}'::jsonb,
    active boolean NOT NULL DEFAULT true,
    create_time bigint NOT NULL,
    update_time bigint NOT NULL,
    CONSTRAINT workflow_definitions_project_script_version_key
        UNIQUE (project_id, script_id, version)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_toonflow_active_workflow_definition
    ON toonflow.workflow_definitions(project_id, script_id)
    WHERE active;

CREATE TABLE IF NOT EXISTS toonflow.workflow_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_definition_id bigint NOT NULL
        REFERENCES toonflow.workflow_definitions(id) ON DELETE RESTRICT,
    project_id bigint NOT NULL REFERENCES toonflow.projects(id) ON DELETE CASCADE,
    script_id bigint NOT NULL REFERENCES toonflow.scripts(id) ON DELETE CASCADE,
    definition_version integer NOT NULL,
    state character varying(32) NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'running', 'success', 'failed', 'cancelled')),
    trigger_type character varying(32) NOT NULL DEFAULT 'manual',
    input jsonb NOT NULL DEFAULT '{}'::jsonb,
    output jsonb,
    error_reason text,
    start_time bigint,
    finish_time bigint,
    create_time bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_toonflow_workflow_runs_project_script
    ON toonflow.workflow_runs(project_id, script_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_toonflow_workflow_runs_state
    ON toonflow.workflow_runs(state, create_time);

CREATE TABLE IF NOT EXISTS toonflow.workflow_node_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_run_id bigint NOT NULL
        REFERENCES toonflow.workflow_runs(id) ON DELETE CASCADE,
    node_id character varying(128) NOT NULL,
    node_type character varying(128) NOT NULL,
    attempt integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
    state character varying(32) NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'blocked', 'running', 'success', 'failed', 'cancelled', 'skipped')),
    input jsonb NOT NULL DEFAULT '{}'::jsonb,
    output jsonb,
    input_hash character varying(64),
    error_reason text,
    start_time bigint,
    finish_time bigint,
    create_time bigint NOT NULL,
    CONSTRAINT workflow_node_runs_run_node_attempt_key
        UNIQUE (workflow_run_id, node_id, attempt)
);

CREATE INDEX IF NOT EXISTS idx_toonflow_workflow_node_runs_state
    ON toonflow.workflow_node_runs(workflow_run_id, state);
