-- Durable execution records for work that runs outside the HTTP gateway.
-- PostgreSQL is the transactional source of truth; JetStream carries only a
-- versioned reference to one of these rows and may redeliver it.

CREATE SEQUENCE IF NOT EXISTS toonflow.task_id_seq AS bigint;

SELECT setval(
    'toonflow.task_id_seq',
    COALESCE((SELECT max(id) + 1 FROM toonflow.tasks), 1),
    false
);

ALTER SEQUENCE toonflow.task_id_seq OWNED BY toonflow.tasks.id;
ALTER TABLE toonflow.tasks
    ALTER COLUMN id SET DEFAULT nextval('toonflow.task_id_seq');

CREATE TABLE IF NOT EXISTS toonflow.distributed_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id uuid NOT NULL DEFAULT gen_random_uuid(),
    task_id bigint NOT NULL,
    kind text NOT NULL,
    trace_id text NOT NULL DEFAULT 'background',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    state text NOT NULL DEFAULT 'queued',
    priority integer NOT NULL DEFAULT 0,
    attempt integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    available_at timestamp with time zone NOT NULL DEFAULT now(),
    published_at timestamp with time zone,
    lease_owner text,
    lease_token uuid,
    lease_until timestamp with time zone,
    heartbeat_at timestamp with time zone,
    result jsonb,
    last_error text,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT distributed_jobs_task_fk
        FOREIGN KEY (task_id)
        REFERENCES toonflow.tasks(id)
        ON DELETE CASCADE,
    CONSTRAINT distributed_jobs_task_unique UNIQUE (task_id),
    CONSTRAINT distributed_jobs_message_unique UNIQUE (message_id),
    CONSTRAINT distributed_jobs_kind_not_blank CHECK (btrim(kind) <> ''),
    CONSTRAINT distributed_jobs_payload_is_object
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT distributed_jobs_state_valid CHECK (
        state IN ('queued', 'running', 'retry', 'succeeded', 'failed', 'canceled')
    ),
    CONSTRAINT distributed_jobs_attempt_valid CHECK (
        attempt >= 0 AND max_attempts > 0 AND attempt <= max_attempts
    ),
    CONSTRAINT distributed_jobs_running_has_lease CHECK (
        state <> 'running'
        OR (lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_until IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_distributed_jobs_dispatch
    ON toonflow.distributed_jobs(priority DESC, available_at, id)
    WHERE state IN ('queued', 'retry') AND published_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_distributed_jobs_expired_lease
    ON toonflow.distributed_jobs(lease_until, id)
    WHERE state = 'running';

CREATE INDEX IF NOT EXISTS idx_distributed_jobs_task_state
    ON toonflow.distributed_jobs(task_id, state);

CREATE TABLE IF NOT EXISTS toonflow.worker_instances (
    instance_id text PRIMARY KEY,
    service text NOT NULL,
    status text NOT NULL DEFAULT 'starting',
    concurrency integer NOT NULL DEFAULT 1,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    heartbeat_at timestamp with time zone NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT worker_instances_service_not_blank CHECK (btrim(service) <> ''),
    CONSTRAINT worker_instances_status_valid CHECK (
        status IN ('starting', 'ready', 'draining', 'stopped')
    ),
    CONSTRAINT worker_instances_concurrency_positive CHECK (concurrency > 0),
    CONSTRAINT worker_instances_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_worker_instances_service_heartbeat
    ON toonflow.worker_instances(service, heartbeat_at DESC);

-- Maintenance work is also claimed with a lease. This replaces the old
-- gateway-startup scan, which could run the same deletion on every replica.
CREATE SEQUENCE IF NOT EXISTS toonflow.storage_cleanup_task_id_seq AS bigint;

SELECT setval(
    'toonflow.storage_cleanup_task_id_seq',
    COALESCE((SELECT max(id) + 1 FROM toonflow.storage_cleanup_tasks), 1),
    false
);

ALTER SEQUENCE toonflow.storage_cleanup_task_id_seq
    OWNED BY toonflow.storage_cleanup_tasks.id;
ALTER TABLE toonflow.storage_cleanup_tasks
    ALTER COLUMN id SET DEFAULT nextval('toonflow.storage_cleanup_task_id_seq'),
    ADD COLUMN IF NOT EXISTS lease_owner text,
    ADD COLUMN IF NOT EXISTS lease_token uuid,
    ADD COLUMN IF NOT EXISTS lease_until timestamp with time zone;

CREATE INDEX IF NOT EXISTS idx_storage_cleanup_tasks_claim
    ON toonflow.storage_cleanup_tasks(state, lease_until, update_time)
    WHERE state IN ('pending', 'running');
