-- Durable same-scene visual identity and state snapshots.
--
-- A scene master owns the stable spatial contract. Scene states describe only
-- durable changes inside that space (for example an intact door becoming
-- broken), while storyboards bind to the state they intend to render. Existing
-- generated storyboard images deliberately remain unclaimed because they were
-- produced before this contract existed.

CREATE UNIQUE INDEX IF NOT EXISTS uq_toonflow_images_id_assets_id
    ON toonflow.images(id, assets_id);

CREATE TABLE IF NOT EXISTS toonflow.scene_masters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL,
    script_id bigint NOT NULL,
    scene_key text NOT NULL,
    name text NOT NULL DEFAULT '',
    scene_asset_id bigint,
    pinned_image_id bigint,
    spatial_prompt text NOT NULL DEFAULT '',
    layout_spec jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'missing_reference',
    source text NOT NULL DEFAULT 'manual',
    revision integer NOT NULL DEFAULT 1,
    create_time bigint NOT NULL DEFAULT
        ((extract(epoch FROM clock_timestamp()) * 1000)::bigint),
    update_time bigint NOT NULL DEFAULT
        ((extract(epoch FROM clock_timestamp()) * 1000)::bigint),
    CONSTRAINT scene_masters_scope_unique
        UNIQUE (project_id, script_id, scene_key),
    CONSTRAINT scene_masters_script_project_fk
        FOREIGN KEY (script_id, project_id)
        REFERENCES toonflow.scripts(id, project_id)
        ON DELETE CASCADE,
    CONSTRAINT scene_masters_scene_asset_fk
        FOREIGN KEY (scene_asset_id)
        REFERENCES toonflow.assets(id)
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT scene_masters_pinned_image_asset_fk
        FOREIGN KEY (pinned_image_id, scene_asset_id)
        REFERENCES toonflow.images(id, assets_id)
        ON DELETE SET NULL (pinned_image_id),
    CONSTRAINT scene_masters_reference_pair_complete
        CHECK (pinned_image_id IS NULL OR scene_asset_id IS NOT NULL),
    CONSTRAINT scene_masters_scene_key_canonical
        CHECK (scene_key ~ '^sc[1-9][0-9]*$'),
    CONSTRAINT scene_masters_layout_spec_is_object
        CHECK (jsonb_typeof(layout_spec) = 'object'),
    CONSTRAINT scene_masters_status_valid
        CHECK (status IN ('ready', 'missing_reference', 'needs_review')),
    CONSTRAINT scene_masters_source_valid
        CHECK (source IN ('manual', 'director', 'agent', 'backfill')),
    CONSTRAINT scene_masters_revision_positive CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS toonflow.scene_states (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_master_id bigint NOT NULL,
    state_key text NOT NULL,
    name text NOT NULL DEFAULT '',
    parent_state_id bigint,
    sequence integer NOT NULL,
    change_summary text NOT NULL DEFAULT '',
    state_prompt text NOT NULL DEFAULT '',
    object_states jsonb NOT NULL DEFAULT '{}'::jsonb,
    source text NOT NULL DEFAULT 'manual',
    revision integer NOT NULL DEFAULT 1,
    create_time bigint NOT NULL DEFAULT
        ((extract(epoch FROM clock_timestamp()) * 1000)::bigint),
    update_time bigint NOT NULL DEFAULT
        ((extract(epoch FROM clock_timestamp()) * 1000)::bigint),
    CONSTRAINT scene_states_master_sequence_unique
        UNIQUE (scene_master_id, sequence),
    CONSTRAINT scene_states_master_key_unique
        UNIQUE (scene_master_id, state_key),
    CONSTRAINT scene_states_id_master_unique
        UNIQUE (id, scene_master_id),
    CONSTRAINT scene_states_master_fk
        FOREIGN KEY (scene_master_id)
        REFERENCES toonflow.scene_masters(id)
        ON DELETE CASCADE,
    CONSTRAINT scene_states_parent_same_master_fk
        FOREIGN KEY (parent_state_id, scene_master_id)
        REFERENCES toonflow.scene_states(id, scene_master_id)
        ON DELETE CASCADE,
    CONSTRAINT scene_states_state_key_canonical
        CHECK (state_key ~ '^[a-z][a-z0-9_-]{0,63}$'),
    CONSTRAINT scene_states_sequence_non_negative CHECK (sequence >= 0),
    CONSTRAINT scene_states_base_parent_contract
        CHECK (
            (state_key = 'base' AND sequence = 0 AND parent_state_id IS NULL)
            OR (state_key <> 'base' AND sequence > 0 AND parent_state_id IS NOT NULL)
        ),
    CONSTRAINT scene_states_parent_not_self
        CHECK (parent_state_id IS NULL OR parent_state_id <> id),
    CONSTRAINT scene_states_object_states_is_object
        CHECK (jsonb_typeof(object_states) = 'object'),
    CONSTRAINT scene_states_source_valid
        CHECK (source IN ('manual', 'director', 'agent', 'backfill', 'system')),
    CONSTRAINT scene_states_revision_positive CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS toonflow.scene_state_references (
    scene_state_id bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    role text NOT NULL DEFAULT 'state',
    asset_id bigint NOT NULL,
    image_id bigint NOT NULL,
    prompt_label text NOT NULL DEFAULT '',
    CONSTRAINT scene_state_references_pkey
        PRIMARY KEY (scene_state_id, sort_order),
    CONSTRAINT scene_state_references_state_image_unique
        UNIQUE (scene_state_id, image_id),
    CONSTRAINT scene_state_references_state_fk
        FOREIGN KEY (scene_state_id)
        REFERENCES toonflow.scene_states(id)
        ON DELETE CASCADE,
    CONSTRAINT scene_state_references_asset_fk
        FOREIGN KEY (asset_id)
        REFERENCES toonflow.assets(id)
        ON DELETE CASCADE,
    CONSTRAINT scene_state_references_image_asset_fk
        FOREIGN KEY (image_id, asset_id)
        REFERENCES toonflow.images(id, assets_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT scene_state_references_role_valid
        CHECK (role IN ('master', 'state', 'object_detail')),
    CONSTRAINT scene_state_references_sort_order_non_negative
        CHECK (sort_order >= 0)
);

ALTER TABLE toonflow.storyboards
    ADD COLUMN IF NOT EXISTS scene_state_id bigint,
    ADD COLUMN IF NOT EXISTS generated_scene_state_id bigint,
    ADD COLUMN IF NOT EXISTS scene_generation_context jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE toonflow.storyboards
SET scene_generation_context = '{}'::jsonb
WHERE scene_generation_context IS NULL
   OR jsonb_typeof(scene_generation_context) <> 'object';

ALTER TABLE toonflow.storyboards
    ALTER COLUMN scene_generation_context SET DEFAULT '{}'::jsonb,
    ALTER COLUMN scene_generation_context SET NOT NULL;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'toonflow.storyboards'::regclass
          AND conname = 'storyboards_scene_state_fk'
    ) THEN
        ALTER TABLE toonflow.storyboards
            ADD CONSTRAINT storyboards_scene_state_fk
            FOREIGN KEY (scene_state_id)
            REFERENCES toonflow.scene_states(id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'toonflow.storyboards'::regclass
          AND conname = 'storyboards_generated_scene_state_fk'
    ) THEN
        ALTER TABLE toonflow.storyboards
            ADD CONSTRAINT storyboards_generated_scene_state_fk
            FOREIGN KEY (generated_scene_state_id)
            REFERENCES toonflow.scene_states(id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'toonflow.storyboards'::regclass
          AND conname = 'storyboards_scene_state_requires_scene_key'
    ) THEN
        ALTER TABLE toonflow.storyboards
            ADD CONSTRAINT storyboards_scene_state_requires_scene_key
            CHECK (
                (scene_state_id IS NULL AND generated_scene_state_id IS NULL)
                OR scene_key IS NOT NULL
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'toonflow.storyboards'::regclass
          AND conname = 'storyboards_scene_generation_context_is_object'
    ) THEN
        ALTER TABLE toonflow.storyboards
            ADD CONSTRAINT storyboards_scene_generation_context_is_object
            CHECK (jsonb_typeof(scene_generation_context) = 'object');
    END IF;
END
$migration$;

-- Create one logical master per persisted canonical scene. A master is ready
-- only when every storyboard has exactly one scene-asset binding, every binding
-- belongs to the storyboard project, all boards select the same asset, and that
-- asset's selected image is complete and addressable. Missing, cross-project,
-- multi-bound, and divergent boards remain unclaimed rather than being guessed.
WITH storyboard_scene_assets AS (
    SELECT storyboard.id AS storyboard_id,
           storyboard.project_id,
           storyboard.script_id,
           storyboard.scene_key,
           count(asset.id) FILTER (WHERE asset.type = 'scene') AS scene_binding_count,
           count(asset.id) FILTER (
               WHERE asset.type = 'scene'
                 AND asset.project_id = storyboard.project_id
           ) AS same_project_scene_binding_count,
           min(asset.id) FILTER (
               WHERE asset.type = 'scene'
                 AND asset.project_id = storyboard.project_id
           ) AS only_same_project_scene_asset_id
    FROM toonflow.storyboards storyboard
    LEFT JOIN toonflow.assets_storyboards binding
      ON binding.storyboard_id = storyboard.id
    LEFT JOIN toonflow.assets asset ON asset.id = binding.asset_id
    WHERE storyboard.scene_key ~ '^sc[1-9][0-9]*$'
    GROUP BY storyboard.id, storyboard.project_id,
             storyboard.script_id, storyboard.scene_key
),
scene_asset_summary AS (
    SELECT board.project_id,
           board.script_id,
           board.scene_key,
           count(*) AS storyboard_count,
           count(*) FILTER (
               WHERE board.scene_binding_count = 1
                 AND board.same_project_scene_binding_count = 1
           ) AS valid_storyboard_count,
           count(DISTINCT board.only_same_project_scene_asset_id) FILTER (
               WHERE board.scene_binding_count = 1
                 AND board.same_project_scene_binding_count = 1
           ) AS selected_asset_count,
           min(board.only_same_project_scene_asset_id) FILTER (
               WHERE board.scene_binding_count = 1
                 AND board.same_project_scene_binding_count = 1
           ) AS only_scene_asset_id,
           sum(board.scene_binding_count) AS total_scene_binding_count
    FROM storyboard_scene_assets board
    GROUP BY board.project_id, board.script_id, board.scene_key
),
selected_masters AS (
    SELECT summary.*,
           summary.valid_storyboard_count = summary.storyboard_count
             AND summary.selected_asset_count = 1 AS has_unanimous_scene_asset
    FROM scene_asset_summary summary
),
resolved_masters AS (
    SELECT selected.*,
           CASE WHEN selected.has_unanimous_scene_asset
                THEN asset.id
                ELSE NULL
           END AS scene_asset_id,
           CASE WHEN selected.has_unanimous_scene_asset
                     AND image.id IS NOT NULL
                THEN image.id
                ELSE NULL
           END AS pinned_image_id,
           asset.name AS asset_name,
           asset.prompt AS asset_prompt,
           asset.description AS asset_description
    FROM selected_masters selected
    LEFT JOIN toonflow.assets asset
      ON asset.id = selected.only_scene_asset_id
     AND asset.project_id = selected.project_id
     AND asset.type = 'scene'
     AND selected.has_unanimous_scene_asset
    LEFT JOIN toonflow.images image
      ON image.id = asset.image_id
     AND image.assets_id = asset.id
     AND image.state = '已完成'
     AND coalesce(image.file_path, '') <> ''
)
INSERT INTO toonflow.scene_masters(
    project_id, script_id, scene_key, name, scene_asset_id, pinned_image_id,
    spatial_prompt, layout_spec, status, source
)
SELECT selected.project_id,
       selected.script_id,
       selected.scene_key,
       coalesce(nullif(selected.asset_name, ''), selected.scene_key),
       selected.scene_asset_id,
       selected.pinned_image_id,
       coalesce(nullif(selected.asset_prompt, ''),
                nullif(selected.asset_description, ''), ''),
       '{}'::jsonb,
       CASE
           WHEN selected.pinned_image_id IS NOT NULL THEN 'ready'
           WHEN selected.has_unanimous_scene_asset THEN 'missing_reference'
           WHEN selected.total_scene_binding_count > 0 THEN 'needs_review'
           ELSE 'missing_reference'
       END,
       'backfill'
FROM resolved_masters selected
ON CONFLICT (project_id, script_id, scene_key) DO NOTHING;

INSERT INTO toonflow.scene_states(
    scene_master_id, state_key, name, parent_state_id, sequence,
    change_summary, state_prompt, object_states, source
)
SELECT master.id,
       'base',
       '初始状态',
       NULL,
       0,
       '',
       '',
       '{}'::jsonb,
       'backfill'
FROM toonflow.scene_masters master
WHERE NOT EXISTS (
    SELECT 1 FROM toonflow.scene_states state
    WHERE state.scene_master_id = master.id AND state.state_key = 'base'
)
ON CONFLICT (scene_master_id, state_key) DO NOTHING;

UPDATE toonflow.storyboards storyboard
SET scene_state_id = state.id
FROM toonflow.scene_masters master
JOIN toonflow.scene_states state
  ON state.scene_master_id = master.id
 AND state.state_key = 'base'
WHERE storyboard.project_id = master.project_id
  AND storyboard.script_id = master.script_id
  AND storyboard.scene_key = master.scene_key
  AND storyboard.scene_state_id IS NULL;

-- A rerun may already have the deferred storyboard-timeline trigger installed.
-- Flush its events before the idempotent index DDL later in this migration.
SET CONSTRAINTS ALL IMMEDIATE;

CREATE OR REPLACE FUNCTION toonflow.bump_scene_state_revision_tree(
    root_state_ids bigint[]
)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    IF root_state_ids IS NULL OR cardinality(root_state_ids) = 0 THEN
        RETURN;
    END IF;

    WITH RECURSIVE descendants(id) AS (
        SELECT DISTINCT root_id
        FROM unnest(root_state_ids) AS roots(root_id)
        WHERE root_id IS NOT NULL
        UNION
        SELECT child.id
        FROM toonflow.scene_states child
        JOIN descendants parent ON child.parent_state_id = parent.id
    )
    UPDATE toonflow.scene_states state
    SET revision = state.revision + 1,
        update_time = (extract(epoch FROM clock_timestamp()) * 1000)::bigint
    WHERE state.id IN (SELECT id FROM descendants)
      AND EXISTS (
          SELECT 1 FROM toonflow.scene_masters master
          WHERE master.id = state.scene_master_id
      );
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_scene_master_integrity()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.scene_asset_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM toonflow.assets asset
        WHERE asset.id = NEW.scene_asset_id
          AND asset.project_id = NEW.project_id
          AND asset.type = 'scene'
    ) THEN
        RAISE EXCEPTION 'scene master asset must be a scene asset from its project'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.pinned_image_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM toonflow.images image
        WHERE image.id = NEW.pinned_image_id
          AND image.assets_id = NEW.scene_asset_id
    ) THEN
        RAISE EXCEPTION 'scene master pinned image must belong to its scene asset'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.pinned_image_id IS NULL AND NEW.status = 'ready' THEN
        NEW.status := 'missing_reference';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF EXISTS (
            SELECT 1
            FROM toonflow.scene_state_references reference
            JOIN toonflow.scene_states state ON state.id = reference.scene_state_id
            JOIN toonflow.assets asset ON asset.id = reference.asset_id
            WHERE state.scene_master_id = OLD.id
              AND asset.project_id <> NEW.project_id
        ) THEN
            RAISE EXCEPTION 'scene master project change would invalidate a state reference'
                USING ERRCODE = '23514';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM toonflow.storyboards storyboard
            JOIN toonflow.scene_states state
              ON state.id = storyboard.scene_state_id
              OR state.id = storyboard.generated_scene_state_id
            WHERE state.scene_master_id = OLD.id
              AND (
                  storyboard.project_id IS DISTINCT FROM NEW.project_id
                  OR storyboard.script_id IS DISTINCT FROM NEW.script_id
                  OR storyboard.scene_key IS DISTINCT FROM NEW.scene_key
              )
        ) THEN
            RAISE EXCEPTION 'scene master scope change would invalidate a storyboard binding'
                USING ERRCODE = '23514';
        END IF;

        IF (NEW.scene_asset_id, NEW.pinned_image_id)
            IS DISTINCT FROM (OLD.scene_asset_id, OLD.pinned_image_id)
        THEN
            NEW.revision := greatest(NEW.revision, OLD.revision + 1);
            NEW.update_time :=
                (extract(epoch FROM clock_timestamp()) * 1000)::bigint;
        END IF;
    END IF;

    RETURN NEW;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_scene_state_integrity()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    target_project_id bigint;
    target_script_id bigint;
    target_scene_key text;
    parent_master_id bigint;
    parent_sequence integer;
BEGIN
    SELECT master.project_id, master.script_id, master.scene_key
    INTO target_project_id, target_script_id, target_scene_key
    FROM toonflow.scene_masters master
    WHERE master.id = NEW.scene_master_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'scene state must belong to an existing scene master'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.parent_state_id IS NOT NULL THEN
        IF NEW.parent_state_id = NEW.id THEN
            RAISE EXCEPTION 'scene state cannot parent itself'
                USING ERRCODE = '23514';
        END IF;

        SELECT parent.scene_master_id, parent.sequence
        INTO parent_master_id, parent_sequence
        FROM toonflow.scene_states parent
        WHERE parent.id = NEW.parent_state_id;

        IF NOT FOUND OR parent_master_id <> NEW.scene_master_id THEN
            RAISE EXCEPTION 'scene state parent must belong to the same scene master'
                USING ERRCODE = '23514';
        END IF;

        IF parent_sequence >= NEW.sequence THEN
            RAISE EXCEPTION 'scene state parent sequence must precede its child'
                USING ERRCODE = '23514';
        END IF;

        IF EXISTS (
            WITH RECURSIVE ancestors(id, parent_state_id) AS (
                SELECT state.id, state.parent_state_id
                FROM toonflow.scene_states state
                WHERE state.id = NEW.parent_state_id
                UNION
                SELECT parent.id, parent.parent_state_id
                FROM toonflow.scene_states parent
                JOIN ancestors child ON parent.id = child.parent_state_id
            )
            SELECT 1 FROM ancestors WHERE id = NEW.id
        ) THEN
            RAISE EXCEPTION 'scene state parent would create a cycle'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF EXISTS (
            SELECT 1
            FROM toonflow.scene_states child
            WHERE child.parent_state_id = OLD.id
              AND (
                  child.scene_master_id <> NEW.scene_master_id
                  OR child.sequence <= NEW.sequence
              )
        ) THEN
            RAISE EXCEPTION 'scene state update would invalidate a child state'
                USING ERRCODE = '23514';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM toonflow.scene_state_references reference
            JOIN toonflow.assets asset ON asset.id = reference.asset_id
            WHERE reference.scene_state_id = OLD.id
              AND asset.project_id <> target_project_id
        ) THEN
            RAISE EXCEPTION 'scene state scope change would invalidate a reference'
                USING ERRCODE = '23514';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM toonflow.storyboards storyboard
            WHERE (
                    storyboard.scene_state_id = OLD.id
                    OR storyboard.generated_scene_state_id = OLD.id
                  )
              AND (
                  storyboard.project_id IS DISTINCT FROM target_project_id
                  OR storyboard.script_id IS DISTINCT FROM target_script_id
                  OR storyboard.scene_key IS DISTINCT FROM target_scene_key
              )
        ) THEN
            RAISE EXCEPTION 'scene state scope change would invalidate a storyboard binding'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    RETURN NEW;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_scene_state_reference_integrity()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM toonflow.scene_states state
        JOIN toonflow.scene_masters master ON master.id = state.scene_master_id
        JOIN toonflow.assets asset
          ON asset.id = NEW.asset_id
         AND asset.project_id = master.project_id
        JOIN toonflow.images image
          ON image.id = NEW.image_id
         AND image.assets_id = asset.id
        WHERE state.id = NEW.scene_state_id
    ) THEN
        RAISE EXCEPTION 'scene state reference must use a paired asset and image from the scene project'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_scene_asset_reverse_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM toonflow.scene_masters master
        WHERE master.scene_asset_id = OLD.id
          AND (NEW.project_id <> master.project_id OR NEW.type <> 'scene')
    ) THEN
        RAISE EXCEPTION 'asset update would invalidate a scene master reference'
            USING ERRCODE = '23514';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM toonflow.scene_state_references reference
        JOIN toonflow.scene_states state ON state.id = reference.scene_state_id
        JOIN toonflow.scene_masters master ON master.id = state.scene_master_id
        WHERE reference.asset_id = OLD.id
          AND NEW.project_id <> master.project_id
    ) THEN
        RAISE EXCEPTION 'asset project update would invalidate a scene state reference'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_scene_image_reverse_binding()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM toonflow.scene_masters master
        WHERE master.pinned_image_id = OLD.id
          AND NEW.assets_id IS DISTINCT FROM master.scene_asset_id
    ) THEN
        RAISE EXCEPTION 'image asset update would invalidate a scene master reference'
            USING ERRCODE = '23514';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM toonflow.scene_state_references reference
        JOIN toonflow.scene_states state ON state.id = reference.scene_state_id
        JOIN toonflow.scene_masters master ON master.id = state.scene_master_id
        LEFT JOIN toonflow.assets asset ON asset.id = NEW.assets_id
        WHERE reference.image_id = OLD.id
          AND (
              asset.id IS NULL
              OR asset.project_id <> master.project_id
          )
    ) THEN
        RAISE EXCEPTION 'image asset update would move a scene state reference outside its project'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.bump_revisions_for_scene_reference()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        PERFORM toonflow.bump_scene_state_revision_tree(ARRAY[NEW.scene_state_id]);
    ELSIF TG_OP = 'DELETE' THEN
        PERFORM toonflow.bump_scene_state_revision_tree(ARRAY[OLD.scene_state_id]);
    ELSE
        PERFORM toonflow.bump_scene_state_revision_tree(
            ARRAY[OLD.scene_state_id, NEW.scene_state_id]
        );
    END IF;

    RETURN NULL;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.bump_revisions_for_scene_image()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    referenced_state_ids bigint[];
BEGIN
    IF (NEW.file_path, NEW.state, NEW.assets_id)
        IS NOT DISTINCT FROM (OLD.file_path, OLD.state, OLD.assets_id)
    THEN
        RETURN NULL;
    END IF;

    IF (NEW.file_path, NEW.state) IS DISTINCT FROM (OLD.file_path, OLD.state) THEN
        SELECT array_agg(DISTINCT reference.scene_state_id)
        INTO referenced_state_ids
        FROM toonflow.scene_state_references reference
        WHERE reference.image_id = NEW.id;

        PERFORM toonflow.bump_scene_state_revision_tree(referenced_state_ids);
    END IF;

    IF (NEW.file_path, NEW.state) IS DISTINCT FROM (OLD.file_path, OLD.state) THEN
        UPDATE toonflow.scene_masters master
        SET status = CASE
                WHEN NEW.state = '已完成'
                     AND coalesce(NEW.file_path, '') <> ''
                THEN 'ready'
                ELSE 'missing_reference'
            END,
            revision = master.revision + 1,
            update_time = (extract(epoch FROM clock_timestamp()) * 1000)::bigint
        WHERE master.pinned_image_id = NEW.id;

        IF NEW.state = '已完成' AND coalesce(NEW.file_path, '') <> '' THEN
            UPDATE toonflow.scene_masters master
            SET pinned_image_id = NEW.id,
                status = 'ready',
                update_time =
                    (extract(epoch FROM clock_timestamp()) * 1000)::bigint
            FROM toonflow.assets asset
            WHERE master.scene_asset_id = asset.id
              AND master.pinned_image_id IS NULL
              AND asset.image_id = NEW.id
              AND NEW.assets_id = asset.id;
        END IF;
    END IF;

    RETURN NULL;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.auto_pin_scene_master_asset_image()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.image_id IS DISTINCT FROM OLD.image_id AND NEW.image_id IS NOT NULL THEN
        UPDATE toonflow.scene_masters master
        SET pinned_image_id = image.id,
            status = 'ready',
            update_time =
                (extract(epoch FROM clock_timestamp()) * 1000)::bigint
        FROM toonflow.images image
        WHERE master.scene_asset_id = NEW.id
          AND master.pinned_image_id IS NULL
          AND image.id = NEW.image_id
          AND image.assets_id = NEW.id
          AND image.state = '已完成'
          AND coalesce(image.file_path, '') <> '';
    END IF;

    RETURN NULL;
END
$function$;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.scene_masters'::regclass
          AND tgname = 'scene_masters_enforce_integrity'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER scene_masters_enforce_integrity
        BEFORE INSERT OR UPDATE ON toonflow.scene_masters
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_scene_master_integrity();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.scene_states'::regclass
          AND tgname = 'scene_states_enforce_integrity'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER scene_states_enforce_integrity
        BEFORE INSERT OR UPDATE ON toonflow.scene_states
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_scene_state_integrity();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.scene_state_references'::regclass
          AND tgname = 'scene_state_references_enforce_integrity'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER scene_state_references_enforce_integrity
        BEFORE INSERT OR UPDATE ON toonflow.scene_state_references
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_scene_state_reference_integrity();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.assets'::regclass
          AND tgname = 'assets_enforce_scene_reverse_scope'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER assets_enforce_scene_reverse_scope
        BEFORE UPDATE OF project_id, type ON toonflow.assets
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_scene_asset_reverse_scope();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.images'::regclass
          AND tgname = 'images_enforce_scene_reverse_binding'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER images_enforce_scene_reverse_binding
        BEFORE UPDATE OF assets_id ON toonflow.images
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_scene_image_reverse_binding();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.scene_state_references'::regclass
          AND tgname = 'scene_state_references_bump_revision_tree'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER scene_state_references_bump_revision_tree
        AFTER INSERT OR UPDATE OR DELETE ON toonflow.scene_state_references
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.bump_revisions_for_scene_reference();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.images'::regclass
          AND tgname = 'images_bump_scene_revisions'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER images_bump_scene_revisions
        AFTER UPDATE OF file_path, state, assets_id ON toonflow.images
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.bump_revisions_for_scene_image();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.assets'::regclass
          AND tgname = 'assets_auto_pin_scene_master_image'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER assets_auto_pin_scene_master_image
        AFTER UPDATE OF image_id ON toonflow.assets
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.auto_pin_scene_master_asset_image();
    END IF;
END
$migration$;

-- A plain state-id foreign key is insufficient because it could bind a board to
-- another project, episode, or scene. Enforce the full logical scope without
-- duplicating scope columns on every state row.
CREATE OR REPLACE FUNCTION toonflow.enforce_storyboard_scene_state_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.scene_state_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM toonflow.scene_states state
        JOIN toonflow.scene_masters master ON master.id = state.scene_master_id
        WHERE state.id = NEW.scene_state_id
          AND master.project_id = NEW.project_id
          AND master.script_id = NEW.script_id
          AND master.scene_key = NEW.scene_key
    ) THEN
        RAISE EXCEPTION 'scene_state_id does not belong to the storyboard scene'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.generated_scene_state_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM toonflow.scene_states state
        JOIN toonflow.scene_masters master ON master.id = state.scene_master_id
        WHERE state.id = NEW.generated_scene_state_id
          AND master.project_id = NEW.project_id
          AND master.script_id = NEW.script_id
          AND master.scene_key = NEW.scene_key
    ) THEN
        RAISE EXCEPTION 'generated_scene_state_id does not belong to the storyboard scene'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END
$function$;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.storyboards'::regclass
          AND tgname = 'storyboards_enforce_scene_state_scope'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER storyboards_enforce_scene_state_scope
        BEFORE INSERT OR UPDATE OF project_id, script_id, scene_key,
            scene_state_id, generated_scene_state_id
        ON toonflow.storyboards
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_storyboard_scene_state_scope();
    END IF;
END
$migration$;

CREATE OR REPLACE FUNCTION toonflow.validate_scene_state_timeline(
    target_project_id bigint,
    target_script_id bigint,
    target_scene_key text
)
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    managed_master_id bigint;
    previous_state_id bigint;
    board record;
BEGIN
    IF target_scene_key IS NULL THEN
        RETURN;
    END IF;

    SELECT master.id
    INTO managed_master_id
    FROM toonflow.scene_masters master
    WHERE master.project_id = target_project_id
      AND master.script_id = target_script_id
      AND master.scene_key = target_scene_key;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    previous_state_id := NULL;
    FOR board IN
        SELECT storyboard.id, storyboard.scene_state_id
        FROM toonflow.storyboards storyboard
        WHERE storyboard.project_id = target_project_id
          AND storyboard.script_id = target_script_id
          AND storyboard.scene_key = target_scene_key
        ORDER BY storyboard.index ASC NULLS LAST, storyboard.id ASC
    LOOP
        IF board.scene_state_id IS NULL THEN
            RAISE EXCEPTION 'managed scene storyboard % has no scene state', board.id
                USING ERRCODE = '23514';
        END IF;

        IF previous_state_id IS NOT NULL
           AND board.scene_state_id <> previous_state_id
           AND NOT EXISTS (
               WITH RECURSIVE ancestors(id, parent_state_id) AS (
                   SELECT state.id, state.parent_state_id
                   FROM toonflow.scene_states state
                   WHERE state.id = board.scene_state_id
                   UNION
                   SELECT parent.id, parent.parent_state_id
                   FROM toonflow.scene_states parent
                   JOIN ancestors child ON parent.id = child.parent_state_id
               )
               SELECT 1
               FROM ancestors
               WHERE id = previous_state_id
           )
        THEN
            RAISE EXCEPTION
                'scene state timeline cannot move from state % to unrelated or ancestor state % at storyboard %',
                previous_state_id, board.scene_state_id, board.id
                USING ERRCODE = '23514';
        END IF;

        previous_state_id := board.scene_state_id;
    END LOOP;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_storyboard_scene_state_timeline()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    PERFORM toonflow.validate_scene_state_timeline(
        NEW.project_id, NEW.script_id, NEW.scene_key
    );

    IF TG_OP = 'UPDATE'
       AND (NEW.project_id, NEW.script_id, NEW.scene_key)
           IS DISTINCT FROM (OLD.project_id, OLD.script_id, OLD.scene_key)
    THEN
        PERFORM toonflow.validate_scene_state_timeline(
            OLD.project_id, OLD.script_id, OLD.scene_key
        );
    END IF;

    RETURN NULL;
END
$function$;

CREATE OR REPLACE FUNCTION toonflow.enforce_state_graph_storyboard_timelines()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    scene_scope record;
BEGIN
    IF (NEW.scene_master_id, NEW.parent_state_id, NEW.sequence)
        IS NOT DISTINCT FROM
       (OLD.scene_master_id, OLD.parent_state_id, OLD.sequence)
    THEN
        RETURN NULL;
    END IF;

    FOR scene_scope IN
        SELECT DISTINCT master.project_id, master.script_id, master.scene_key
        FROM toonflow.scene_masters master
        WHERE master.id IN (OLD.scene_master_id, NEW.scene_master_id)
    LOOP
        PERFORM toonflow.validate_scene_state_timeline(
            scene_scope.project_id,
            scene_scope.script_id,
            scene_scope.scene_key
        );
    END LOOP;

    IF NEW.parent_state_id IS DISTINCT FROM OLD.parent_state_id
       OR NEW.sequence IS DISTINCT FROM OLD.sequence
    THEN
        PERFORM toonflow.bump_scene_state_revision_tree(ARRAY[NEW.id]);
    END IF;

    RETURN NULL;
END
$function$;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.storyboards'::regclass
          AND tgname = 'storyboards_enforce_scene_state_timeline'
          AND NOT tgisinternal
    ) THEN
        CREATE CONSTRAINT TRIGGER storyboards_enforce_scene_state_timeline
        AFTER INSERT OR UPDATE ON toonflow.storyboards
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_storyboard_scene_state_timeline();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'toonflow.scene_states'::regclass
          AND tgname = 'scene_states_enforce_storyboard_timelines'
          AND NOT tgisinternal
    ) THEN
        CREATE CONSTRAINT TRIGGER scene_states_enforce_storyboard_timelines
        AFTER UPDATE ON toonflow.scene_states
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION toonflow.enforce_state_graph_storyboard_timelines();
    END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS idx_toonflow_scene_masters_status
    ON toonflow.scene_masters(project_id, script_id, status, scene_key);

CREATE INDEX IF NOT EXISTS idx_toonflow_scene_masters_scene_asset
    ON toonflow.scene_masters(scene_asset_id)
    WHERE scene_asset_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_toonflow_scene_states_master_sequence
    ON toonflow.scene_states(scene_master_id, sequence, id);

CREATE INDEX IF NOT EXISTS idx_toonflow_scene_state_references_asset
    ON toonflow.scene_state_references(asset_id, image_id, scene_state_id);

CREATE INDEX IF NOT EXISTS idx_toonflow_storyboards_scene_state
    ON toonflow.storyboards(scene_state_id)
    WHERE scene_state_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_toonflow_storyboards_generated_scene_state
    ON toonflow.storyboards(generated_scene_state_id)
    WHERE generated_scene_state_id IS NOT NULL;

-- Extend released runtime skills from this migration. The marker makes the
-- append idempotent and avoids rewriting user-edited text on a later rerun.
WITH skill_additions(path, addition) AS (
    VALUES
    (
        'production_execution_director_plan.md',
        $scene_consistency$

<!-- scene-consistency-v1 -->
## 场内空间与物件状态契约（强制）

- `sceneKey` 只表示同一连续时空，固定空间结构、门窗、固定家具和物件锚点；机位、景别、人物动作变化不得创建新场。
- 每场初始状态键固定为 `base`。只有门、桌子等物件发生会持续影响后续镜头的实体变化时才创建新状态，例如 `sc1-state1`、`sc1-door-broken`；同场损坏不等于换场。
- `sceneStateDescription` 必须描述该版本完整可见状态及相对 `sceneStateParentKey` 的持久变化，不得根据未写明内容猜测破坏或修复。
- 在 `<scriptPlan>` 的逐场注意事项后追加“场内状态时间线”：`场次 | sceneStateKey | sceneStateParentKey | sceneStateDescription | 生效剧情点`；无持久变化的场也必须保留 `base` 一行。
$scene_consistency$
    ),
    (
        'production_execution_storyboard_table.md',
        $scene_consistency$

<!-- scene-consistency-v1 -->
## 场景状态落镜契约（强制）

- 每个片段必须在标题后写 `**sceneStateKey**：scN-stateM`、`**sceneStateParentKey**：前态键（`base` 为 `null`）与 `**sceneStateDescription**：...`，取自导演规划的场内状态时间线。
- 同场镜头必须保持同一空间母版和固定物件位置，只允许机位、景别、人物姿态与动作变化。
- 门、桌子或其他物件被破坏仍属于原场；发生变化的镜头绑定变化后的状态版本，后续镜头持续沿用，直到导演规划明确出现下一状态或换场。
- 禁止用上一镜画面臆测状态，禁止把尚未发生的损坏提前到更早分镜，也禁止在后续镜头中无故恢复。
$scene_consistency$
    ),
    (
        'production_execution_storyboard_panel.md',
        $scene_consistency$

<!-- scene-consistency-v1 -->
## 场景状态写入契约（强制）

- 每次 `add_flowData_storyboard` 都必须同时传入规范 `sceneKey`、对应的 `sceneStateKey`、`sceneStateParentKey`（`base` 传 `null`）和完整 `sceneStateDescription`；不得用 track 代替场次或状态。
- 同一 `sceneStateKey` 的所有分镜共享同一场景母版、空间锚点和物件状态；prompt 只改变机位、景别、人物动作与表情。
- 物件发生持续性破坏时，从该分镜起使用导演规划给出的下一状态；后续镜头必须继续使用该状态，禁止自动恢复。
- 场景母版和状态参考图由生成层作为托管参考追加，现有 `associateAssetsIds` 的 `@图N` 顺序不得自行重排。

示例：`add_flowData_storyboard({ sceneKey: "sc1", sceneStateKey: "sc1-state1", sceneStateParentKey: "base", sceneStateDescription: "北墙木门断裂倒向室内，左侧木桌仍完好", ... })`
$scene_consistency$
    )
),
rewritten_skills AS (
    SELECT skill.id,
           skill.content || addition.addition AS content
    FROM toonflow.skill_list skill
    JOIN skill_additions addition ON addition.path = skill.path
    WHERE position('<!-- scene-consistency-v1 -->' IN skill.content) = 0
)
UPDATE toonflow.skill_list skill
SET content = rewritten.content,
    md5 = md5(rewritten.content),
    update_time = (extract(epoch FROM clock_timestamp()) * 1000)::bigint
FROM rewritten_skills rewritten
WHERE rewritten.id = skill.id;
