create schema if not exists toonflow;

create table if not exists toonflow.projects (
    id bigint primary key,
    project_type varchar(64) not null default '',
    image_model varchar(128) not null default '',
    image_quality varchar(64) not null default '',
    video_model varchar(128) not null default '',
    name text not null,
    intro text not null default '',
    type text not null default '',
    art_style text not null default '',
    director_manual text not null default '',
    mode text not null default '',
    video_ratio text not null default '',
    user_id uuid references system.users(id) on delete set null,
    create_time bigint not null,
    update_time bigint not null
);

create table if not exists toonflow.art_styles (
    id bigint primary key,
    name varchar(128) not null,
    file_url text not null default '',
    label text not null default '',
    prompt text not null default '',
    create_time bigint not null default (floor(extract(epoch from clock_timestamp()) * 1000)::bigint)
);

create table if not exists toonflow.agent_deployments (
    id bigint primary key generated by default as identity,
    key varchar(128) not null unique,
    description text not null default '',
    name varchar(128) not null,
    temperature integer not null default 1,
    max_output_tokens integer not null default 0,
    disabled boolean not null default false
);

create table if not exists toonflow.settings (
    key text primary key,
    value text not null
);

create table if not exists toonflow.tasks (
    id bigint primary key,
    project_id bigint references toonflow.projects(id) on delete cascade,
    task_class varchar(128) not null default '',
    related_objects varchar(255) not null default '',
    model varchar(128) not null default '',
    description text not null default '',
    state varchar(64) not null default '',
    start_time bigint,
    reason text
);

create table if not exists toonflow.prompts (
    id bigint primary key generated by default as identity,
    name varchar(128) not null,
    type varchar(128) not null,
    data text not null default '',
    use_data text
);

create table if not exists toonflow.novels (
    id bigint primary key,
    chapter_index integer not null,
    reel text not null default '',
    chapter text not null default '',
    chapter_data text not null default '',
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    event_state integer not null default 0,
    event text,
    error_reason text,
    create_time bigint not null
);

create table if not exists toonflow.events (
    id bigint primary key,
    name varchar(255) not null,
    detail text not null default '',
    create_time bigint not null
);

create table if not exists toonflow.event_chapters (
    id bigint primary key generated by default as identity,
    event_id bigint not null references toonflow.events(id) on delete cascade,
    novel_id bigint not null references toonflow.novels(id) on delete cascade
);

create table if not exists toonflow.assets (
    id bigint primary key,
    name text not null default '',
    prompt text not null default '',
    remark text,
    type text not null default '',
    description text not null default '',
    script_id bigint,
    image_id bigint,
    parent_asset_id bigint,
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    flow_id bigint,
    start_time bigint,
    prompt_state varchar(64),
    audio_bind_state integer,
    prompt_error_reason text
);

create table if not exists toonflow.images (
    id bigint primary key,
    file_path text,
    type text,
    assets_id bigint references toonflow.assets(id) on delete cascade,
    model text,
    resolution text,
    state text,
    error_reason text
);

alter table toonflow.assets
    add constraint fk_toonflow_assets_image
    foreign key (image_id) references toonflow.images(id) on delete set null;

create table if not exists toonflow.scripts (
    id bigint primary key,
    name text not null,
    content text not null default '',
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    extract_state integer,
    create_time bigint not null,
    error_reason text
);

create table if not exists toonflow.video_tracks (
    id bigint primary key,
    video_id bigint,
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    script_id bigint references toonflow.scripts(id) on delete cascade,
    state text,
    reason text,
    prompt text,
    select_video_id bigint,
    duration integer
);

create table if not exists toonflow.image_flows (
    id bigint primary key,
    flow_data jsonb not null default '{}'::jsonb
);

create table if not exists toonflow.storyboards (
    id bigint primary key,
    script_id bigint not null references toonflow.scripts(id) on delete cascade,
    prompt text not null default '',
    file_path text,
    duration text,
    state text,
    track_id bigint references toonflow.video_tracks(id) on delete set null,
    reason text,
    track text,
    video_desc text,
    should_generate_image integer not null default 1,
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    flow_id bigint references toonflow.image_flows(id) on delete set null,
    index integer,
    create_time bigint not null
);

create table if not exists toonflow.agent_work_data (
    id bigint primary key generated by default as identity,
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    episodes_id bigint not null references toonflow.scripts(id) on delete cascade,
    key varchar(128) not null,
    data jsonb not null default '{}'::jsonb,
    create_time bigint not null,
    update_time bigint not null,
    unique(project_id, episodes_id, key)
);

create table if not exists toonflow.videos (
    id bigint primary key,
    file_path text,
    error_reason text,
    time integer,
    state text,
    script_id bigint references toonflow.scripts(id) on delete cascade,
    project_id bigint not null references toonflow.projects(id) on delete cascade,
    video_track_id bigint references toonflow.video_tracks(id) on delete set null
);

create table if not exists toonflow.assets_storyboards (
    storyboard_id bigint not null references toonflow.storyboards(id) on delete cascade,
    asset_id bigint not null references toonflow.assets(id) on delete cascade,
    primary key (storyboard_id, asset_id)
);

create table if not exists toonflow.script_assets (
    script_id bigint not null references toonflow.scripts(id) on delete cascade,
    asset_id bigint not null references toonflow.assets(id) on delete cascade,
    primary key (script_id, asset_id)
);

create table if not exists toonflow.skill_list (
    id text primary key,
    md5 text not null,
    path text not null,
    name text not null,
    description text not null default '',
    embedding text,
    type text not null,
    create_time bigint not null,
    update_time bigint not null,
    state integer not null
);

insert into toonflow.settings (key, value) values
    ('messagesPerSummary', '10'),
    ('shortTermLimit', '5'),
    ('summaryMaxLength', '500'),
    ('summaryLimit', '10'),
    ('ragLimit', '3'),
    ('deepRetrieveSummaryLimit', '5'),
    ('modelOnnxFile', '["all-MiniLM-L6-v2", "onnx", "model_fp16.onnx"]'),
    ('modelDtype', 'fp16'),
    ('switchAiDevTool', '0')
on conflict (key) do nothing;

insert into toonflow.agent_deployments
    (key, name, description, disabled, temperature, max_output_tokens)
values
    ('scriptAgent', '剧本Agent', '用于读取原文生成故事骨架、改编策略，建议使用具备强大文本理解和生成能力的模型', false, 1, 0),
    ('productionAgent', '生产Agent', '对工作流进行调度和管理，建议使用具备较强的逻辑推理和任务管理能力的模型', false, 1, 0),
    ('universalAi', '通用AI', '用于小说事件提取、资产提示词生成、台词提取等边缘功能，建议使用具备较强文本处理能力的模型', false, 1, 0),
    ('ttsDubbing', 'TTS配音', '根据剧本内容生成角色配音，支持多种声音风格和情绪', true, 1, 0),
    ('scriptAgent:decisionAgent', '剧本Agent:决策层', '决策层', false, 1, 0),
    ('scriptAgent:supervisionAgent', '剧本Agent:监督层', '监督层', false, 1, 0),
    ('scriptAgent:storySkeletonAgent', '剧本Agent:故事骨架', '故事骨架生成', false, 1, 0),
    ('scriptAgent:adaptationStrategyAgent', '剧本Agent:改编策略', '改编策略生成', false, 1, 0),
    ('scriptAgent:scriptAgent', '剧本Agent:剧本生成', '剧本生成', false, 1, 0),
    ('productionAgent:decisionAgent', '生产Agent:决策层', '决策层', false, 1, 0),
    ('productionAgent:supervisionAgent', '生产Agent:监督层', '监督层', false, 1, 0),
    ('productionAgent:deriveAssetsAgent', '生产Agent:衍生资产', '衍生资产', false, 1, 0),
    ('productionAgent:generateAssetsAgent', '生产Agent:生成资产', '生成资产', false, 1, 0),
    ('productionAgent:directorPlanAgent', '生产Agent:导演规划', '导演规划', false, 1, 0),
    ('productionAgent:storyboardGenAgent', '生产Agent:分镜生成', '分镜生成', false, 1, 0),
    ('productionAgent:storyboardPanelAgent', '生产Agent:分镜面板', '分镜面板生成', false, 1, 0),
    ('productionAgent:storyboardTableAgent', '生产Agent:分镜表格', '分镜表格生成', false, 1, 0)
on conflict (key) do nothing;

create index if not exists idx_toonflow_projects_user on toonflow.projects(user_id);
create index if not exists idx_toonflow_novels_project on toonflow.novels(project_id, chapter_index);
create index if not exists idx_toonflow_scripts_project on toonflow.scripts(project_id);
create index if not exists idx_toonflow_assets_project on toonflow.assets(project_id);
create index if not exists idx_toonflow_storyboards_script on toonflow.storyboards(script_id, index);
create index if not exists idx_toonflow_tasks_project on toonflow.tasks(project_id);
