create table if not exists toonflow.creative_manuals (
    id bigint primary key generated by default as identity,
    kind varchar(32) not null check (kind in ('visual','director')),
    name varchar(255) not null,
    path varchar(255) not null,
    images jsonb not null default '[]'::jsonb,
    data jsonb not null default '[]'::jsonb,
    create_time bigint not null,
    update_time bigint not null,
    unique(kind,path)
);

insert into system_menu (id,name,permission,type,sort,parent_id,path,icon,component,component_name,status,visible,keep_alive,always_show,creator,updater)
values (20007,'创作手册','toon:project:read',2,2,20000,'manuals','lucide:notebook-tabs','toonflow/manuals/index','ToonflowManuals',0,true,true,true,'system','system')
on conflict(id) do update set name=excluded.name,permission=excluded.permission,type=excluded.type,sort=excluded.sort,parent_id=excluded.parent_id,path=excluded.path,icon=excluded.icon,component=excluded.component,component_name=excluded.component_name,status=excluded.status,visible=excluded.visible,keep_alive=excluded.keep_alive,always_show=excluded.always_show,update_time=current_timestamp,deleted=false;

update system_menu set sort=sort+1,update_time=current_timestamp where parent_id=20000 and id between 20002 and 20005;

insert into system_role_menu(id,role_id,menu_id,creator,updater,tenant_id)
select 220007,role.id,20007,'system','system',NULL from system_role role where role.code='super_admin'
and not exists(select 1 from system_role_menu existing where existing.role_id=role.id and existing.menu_id=20007 and existing.deleted=false);
