create table if not exists toonflow.agent_run_events (
    id bigint primary key generated by default as identity,
    run_id bigint not null references toonflow.agent_runs(id) on delete cascade,
    event_type varchar(32) not null,
    data jsonb not null default '{}'::jsonb,
    create_time bigint not null
);
create index if not exists idx_toonflow_agent_run_events_cursor on toonflow.agent_run_events(run_id,id);
