[package]
name = "rust-toon-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
axum.workspace = true
chrono.workspace = true
futures-util.workspace = true
rust-toon-framework-common.workspace = true
rust-toon-framework-database.workspace = true
rust-toon-framework-mq.workspace = true
rust-toon-framework-telemetry.workspace = true
rust-toon-toon-server.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["process", "sync", "time"] }
tracing.workspace = true
uuid.workspace = true
